apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: iothub-private-store
  namespace: keel-system
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: tkeel-middleware-redis-master:6379
    - name: redisPassword
      secretKeyRef:
        key: redis-password
        name: tkeel-middleware-redis