apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/vendor: kubesphere
  name: tkeel-iothub-metrics
  namespace: keel-system
spec:
  endpoints:
    - interval: 1m
      path: /metrics
      port: http
      scheme: http
      scrapeTimeout: 10s
  selector:
    matchLabels:
      tkeel.io/prometheus: true
      app: {{ include "iothub.name" . }}