apiVersion: v1
kind: Service
metadata:
  name: {{ include "iothub.fullname" . }}
  labels:
    {{- include "iothub.labels" . | nindent 4 }}
    - tkeel.io/prometheus: true
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    -port: 8080
      targetport: http
      protocol: TCP
      name: name
  selector:
    app: {{ include "iothub.name" . }}
