apiVersion: v1
kind: Service
metadata:
  name: {{ include "iothub.fullname" . }}
  labels:
    {{- include "iothub.labels" . | nindent 4 }}
    tkeel.io/prometheus: 'true'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9000
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "iothub.name" . }}
